apiVersion: v1
kind: Service
metadata:
  name: auth-redis
  labels:
    app: auth
spec:
  ports:
  - port: 6379
  selector:
    app: auth
    tier: redis
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  labels:
    app: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-redis
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
        tier: redis
    spec:
      containers:
      - image: redis:latest
        name: redis
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-pass
              key: test123
        ports:
        - containerPort: 6379
          name: auth
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /var/lib/redis
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: redis-pv-claim