apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth
spec:
  ports:
  - port: 8081
  selector:
    app: auth-service
    tier: service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
      tier: service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-service
        tier: service
    spec:
      containers:
      - image: lautaroblasco23/authservice
        name: auth-service
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-pass
              key: password
        ports:
        - containerPort: 8081
          name: auth-service